import type { FrontendDesignFramework, MaterialAsset, MaterialSource } from "@/lib/types";

export const ADDITIONAL_MATERIAL_SOURCES: MaterialSource[] = [
  {
    id: "gsap",
    name: "GSAP",
    href: "https://gsap.com/",
    kind: "motion-library",
    signal: "高级 Web 动效编排",
    note: "用于学习 timeline、scroll trigger、状态转场和复杂品牌动效的工程化组织方式。",
  },
  {
    id: "motion",
    name: "Motion",
    href: "https://motion.dev/",
    kind: "motion-library",
    signal: "React 动效状态管理",
    note: "用于把微交互、布局过渡和组件状态变化做成 React 可维护动画。",
  },
  {
    id: "react-bits",
    name: "React Bits",
    href: "https://www.reactbits.dev/",
    kind: "component-library",
    signal: "动效组件灵感",
    note: "用于参考文本、背景、卡片、交互组件如何以代码化方式复现视觉效果。",
  },
  {
    id: "lottiefiles",
    name: "LottieFiles",
    href: "https://lottiefiles.com/",
    kind: "motion-library",
    signal: "矢量动图素材",
    note: "用于把复杂插画动效、加载状态和品牌动画作为轻量可嵌入资源。",
  },
  {
    id: "rive",
    name: "Rive",
    href: "https://rive.app/",
    kind: "motion-library",
    signal: "交互式实时动画",
    note: "用于学习状态机驱动的互动动画，适合游戏化控件、角色反馈和品牌微交互。",
  },
  {
    id: "codrops",
    name: "Codrops",
    href: "https://tympanus.net/codrops/",
    kind: "creative-tech",
    signal: "创意前端实验",
    note: "用于学习 shader、滚动叙事、菜单转场、图像变形等实验型前端视觉技术。",
  },
  {
    id: "typewolf",
    name: "Typewolf",
    href: "https://www.typewolf.com/",
    kind: "typography-system",
    signal: "网页字体搭配",
    note: "用于学习高质量网站如何搭配字体、字号、行距和品牌气质。",
  },
  {
    id: "fonts-in-use",
    name: "Fonts In Use",
    href: "https://fontsinuse.com/",
    kind: "typography-system",
    signal: "真实字体使用案例",
    note: "用于从真实品牌、出版和数字产品中提取字体角色分工。",
  },
  {
    id: "fontshare",
    name: "Fontshare",
    href: "https://www.fontshare.com/",
    kind: "typography-system",
    signal: "免费高质量字体",
    note: "用于挑选可商用、品牌感更强的英文字体，并配合中文系统字体。",
  },
  {
    id: "google-fonts",
    name: "Google Fonts",
    href: "https://fonts.google.com/",
    kind: "typography-system",
    signal: "Web 字体与变量字体",
    note: "用于校准字体加载、fallback、变量字体轴和跨平台可用性。",
  },
  {
    id: "shadcn-ui",
    name: "shadcn/ui",
    href: "https://ui.shadcn.com/",
    kind: "component-library",
    signal: "可复制组件系统",
    note: "用于学习可组合组件、主题 token、表单、弹窗和后台工具界面的工程结构。",
  },
  {
    id: "radix-ui",
    name: "Radix UI",
    href: "https://www.radix-ui.com/",
    kind: "component-library",
    signal: "无样式可访问组件",
    note: "用于保证弹窗、菜单、popover、tabs 等交互组件的键盘和语义基础。",
  },
  {
    id: "material-design",
    name: "Material Design",
    href: "https://m3.material.io/",
    kind: "design-system",
    signal: "成熟设计系统原则",
    note: "用于学习组件状态、色彩 token、排版层级、motion 和可访问性规范。",
  },
  {
    id: "apple-hig",
    name: "Apple HIG",
    href: "https://developer.apple.com/design/human-interface-guidelines/",
    kind: "design-system",
    signal: "平台级交互原则",
    note: "用于校准导航、层级、输入、反馈、空间感和高质量产品细节。",
  },
  {
    id: "linear",
    name: "Linear",
    href: "https://linear.app/",
    kind: "product-ui",
    signal: "高密度 SaaS 产品质感",
    note: "用于学习命令式工作流、键盘优先、低噪音视觉层级和高频操作效率。",
  },
  {
    id: "nngroup",
    name: "Nielsen Norman Group",
    href: "https://www.nngroup.com/",
    kind: "ux-research",
    signal: "用户体验研究框架",
    note: "用于把视觉灵感校准到可理解性、可发现性、反馈、错误恢复和信息架构。",
  },
  {
    id: "baymard",
    name: "Baymard Institute",
    href: "https://baymard.com/",
    kind: "ux-research",
    signal: "电商与表单体验研究",
    note: "用于学习真实转化流程、表单错误、筛选、结账和商品信息结构的避坑规则。",
  },
  {
    id: "magic-ui",
    name: "Magic UI",
    href: "https://magicui.design/",
    kind: "component-library",
    signal: "React/Tailwind/Motion 动效组件",
    note: "用于学习设计工程师如何把 landing page 的光效、文字动效、背景和交互做成可复制组件。",
  },
  {
    id: "aceternity",
    name: "Aceternity UI",
    href: "https://ui.aceternity.com/",
    kind: "component-library",
    signal: "高级 Tailwind + Motion 组件块",
    note: "用于拆解 Hero、Bento、Parallax、Glare、Canvas、Text Reveal 等强视觉组件如何工程化。",
  },
  {
    id: "twenty-first",
    name: "21st.dev",
    href: "https://21st.dev/",
    kind: "component-library",
    signal: "社区 React 组件与模板检索",
    note: "用于按 Heroes、AI Chats、Pricing、Cards、Navigation 等产品模块寻找可迁移组件结构。",
  },
  {
    id: "animata",
    name: "Animata",
    href: "https://animata.design/",
    kind: "motion-library",
    signal: "开源动画 React 组件",
    note: "用于学习可复制的动效组件如何处理可访问性、reduced-motion、真实产品场景和跨框架落地。",
  },
  {
    id: "hover-dev",
    name: "Hover.dev",
    href: "https://www.hover.dev/",
    kind: "motion-library",
    signal: "Hover/微交互动效模板",
    note: "用于提取 hover、cursor、card、button、text reveal 等局部微交互模式。",
  },
  {
    id: "uiverse",
    name: "Uiverse",
    href: "https://uiverse.io/",
    kind: "component-library",
    signal: "开源 UI 元素库",
    note: "用于参考按钮、加载、卡片、表单、切换器等小型 UI 元素的状态和视觉细节。",
  },
  {
    id: "spline",
    name: "Spline",
    href: "https://spline.design/",
    kind: "creative-tech",
    signal: "浏览器 3D 交互设计",
    note: "用于学习 3D hero、产品展示、交互式场景和 WebGL 资产如何融入前端界面。",
  },
];

export const DESIGN_FRAMEWORKS: FrontendDesignFramework[] = [
  {
    id: "state-first-motion",
    title: "状态优先的动效系统",
    category: "motion",
    sourceIds: ["pageflows", "gsap", "motion", "rive"],
    coreIdea: "顶尖动效不是装饰，而是让用户知道系统正在做什么、下一步该做什么。",
    thinkingModel: ["先列状态：idle/loading/success/error/empty", "再定义触发：点击、滚动、hover、数据返回", "最后定义降级：reduced-motion 和移动端简化"],
    transferablePatterns: ["生成中 shimmer", "成功 check reveal", "错误恢复入口", "滚动错峰 reveal", "hover 不改变布局的微反馈"],
    frontendImplementation: ["用状态机或明确枚举管理组件状态", "动画只改变 transform/opacity/filter", "复杂时间线用 GSAP，组件级动效用 Motion", "所有动效提供 prefers-reduced-motion"],
    evaluationQuestions: ["动效是否解释状态", "是否会阻碍阅读", "是否能被关闭或降级", "是否避免 layout shift"],
    avoidWhen: ["表格密集操作", "用户需要快速比较数据", "动效只是为了炫"],
  },
  {
    id: "evidence-led-ui",
    title: "证据驱动的 UI 推荐卡片",
    category: "ui",
    sourceIds: ["pageflows", "mobbin", "shadcn-ui", "radix-ui"],
    coreIdea: "素材库不能只展示图片，必须展示来源、适用场景、避坑和可执行规则。",
    thinkingModel: ["每个素材先回答为什么推荐", "再说明适合谁和不适合谁", "最后转成组件、状态和 token"],
    transferablePatterns: ["来源徽标", "适用标签", "避坑提示", "实现规则", "收藏/导出/复制 prompt"],
    frontendImplementation: ["卡片固定高度和稳定预览比例", "详情抽屉展示完整证据", "外链和内部实现规则分离", "键盘可访问的菜单和收藏操作"],
    evaluationQuestions: ["用户能否追溯来源", "是否给出前端落地动作", "是否避免只像灵感墙", "卡片是否可比较"],
    avoidWhen: ["纯视觉 moodboard", "版权无法确认的图片复制", "没有决策理由的收藏墙"],
  },
  {
    id: "density-ladder",
    title: "信息密度阶梯",
    category: "layout",
    sourceIds: ["mobbin", "linear", "apple-hig", "material-design"],
    coreIdea: "专业工具的高级感来自清晰密度，而不是空白或卡片堆叠。",
    thinkingModel: ["首屏只保留主任务", "次级信息进入右侧/底部面板", "重复动作靠列表和表格", "移动端保留路径不保留所有列"],
    transferablePatterns: ["左侧导航 + 主工作区", "双栏 Agent + 结果", "列表优先的历史记录", "可折叠详情面板"],
    frontendImplementation: ["用 grid minmax 定义布局边界", "固定工具栏高度和滚动区域", "卡片/表格只选一种主表达", "小屏转为单列任务流"],
    evaluationQuestions: ["第一眼是否知道主任务", "是否支持快速扫读", "是否有稳定滚动容器", "移动端是否无横向溢出"],
    avoidWhen: ["品牌叙事长页", "纯作品展示", "需要强情绪视觉而不是操作效率"],
  },
  {
    id: "semantic-color-tokens",
    title: "语义色彩 Token 框架",
    category: "color",
    sourceIds: ["huemint", "material-design", "linear"],
    coreIdea: "配色不是选漂亮颜色，而是定义背景、文字、边框、品牌、状态和强调层级。",
    thinkingModel: ["先定中性色和文字对比", "再定主色和辅助色", "最后定 success/warning/error/info", "浅色和深色分开校准"],
    transferablePatterns: ["品牌交叉配色", "低透明度氛围渐变", "状态色不复用品牌色", "图表色和操作色分离"],
    frontendImplementation: ["使用 CSS variables 或 Tailwind token", "每个 token 有语义名", "关键文本过 WCAG 对比度", "渐变只做背景氛围不压文字"],
    evaluationQuestions: ["颜色是否支持任务层级", "是否有足够对比", "是否能扩展到暗色模式", "是否避免一页一种颜色"],
    avoidWhen: ["已有严格品牌手册且不可改", "医疗金融合规色彩必须审核", "用渐变掩盖信息架构问题"],
  },
  {
    id: "typographic-role-split",
    title: "字体角色分工",
    category: "typography",
    sourceIds: ["typewolf", "fonts-in-use", "fontshare", "google-fonts"],
    coreIdea: "顶尖网页排版会给标题、正文、标签、数字和按钮分配不同角色，而不是全站一个字号。",
    thinkingModel: ["中文优先保证阅读", "英文用于品牌和产品名", "数字用 tabular 对齐", "控件文字独立于正文"],
    transferablePatterns: ["Hero 标题强对比", "正文 1.6 行高", "标签 11-13px 半粗", "按钮固定 min-width", "中英切换不跳版"],
    frontendImplementation: ["定义 font-family fallback 链", "标题用 clamp 但不按 viewport 线性缩放", "按钮/标签单独设 line-height", "font-display 与预加载策略明确"],
    evaluationQuestions: ["中文是否自然", "长文本是否易读", "控件是否像系统 UI", "数字是否对齐", "中英混排是否稳定"],
    avoidWhen: ["盲目引入大字体文件", "负字距", "标题压缩内容", "英文字体直接套中文"],
  },
  {
    id: "creative-code-boundary",
    title: "创意代码的产品边界",
    category: "motion",
    sourceIds: ["codrops", "godly", "awwwards", "react-bits"],
    coreIdea: "创意前端效果要被产品目标约束：可读、可控、可维护、可降级。",
    thinkingModel: ["先定义记忆点", "再定义效果存在的位置", "只把复杂效果放在高价值区域", "其他区域保持克制"],
    transferablePatterns: ["首屏粒子/Shader 氛围", "图像 hover distortion", "文本 reveal", "案例转场", "局部背景互动"],
    frontendImplementation: ["CSS 能做就不用 WebGL", "复杂效果隔离成独立组件", "懒加载重型动画", "保留静态 fallback"],
    evaluationQuestions: ["效果是否提升记忆点", "是否影响 LCP/CLS", "是否可维护", "是否有静态替代"],
    avoidWhen: ["后台工具主流程", "低端设备用户多", "SEO 和性能是第一目标"],
  },
  {
    id: "research-backed-inspiration",
    title: "研究校准的灵感迁移",
    category: "ui",
    sourceIds: ["nngroup", "baymard", "pageflows", "mobbin"],
    coreIdea: "顶尖灵感不能直接复制外观，必须先经过任务、用户、信息层级和错误路径校准。",
    thinkingModel: ["先识别用户任务", "再抽象交互结构", "只迁移可解释的模式", "最后用可发现性和错误恢复验收"],
    transferablePatterns: ["空状态指导", "表单错误定位", "筛选条件可撤销", "关键 CTA 可见", "步骤进度清晰"],
    frontendImplementation: ["为每个模式写状态枚举", "错误信息靠近字段", "筛选 chip 支持单项移除", "CTA 在移动端保持可达"],
    evaluationQuestions: ["用户是否知道当前在哪里", "下一步是否明显", "错误是否可恢复", "灵感是否服务任务而不是装饰"],
    avoidWhen: ["只做视觉 moodboard", "没有明确用户任务", "需求仍停留在风格词"],
  },
  {
    id: "copyable-component-to-product",
    title: "可复制组件到真实产品",
    category: "ui",
    sourceIds: ["magic-ui", "aceternity", "twenty-first", "animata", "shadcn-ui"],
    coreIdea: "现代组件库的价值不在复制外观，而在提取组件边界、状态、token 和内容结构。",
    thinkingModel: ["先判断组件服务哪个用户任务", "再抽象 props/data/state", "替换默认视觉 token", "最后加入空态、错误态和移动端规则"],
    transferablePatterns: ["Hero 光效组件", "Bento 功能块", "AI Chat 面板", "Pricing/Feature 模块", "Text reveal 与渐进展示"],
    frontendImplementation: ["组件复制前先写数据模型", "动画参数集中为 token", "保留 keyboard/focus/reduced-motion", "避免把模板 copy 成不可维护的大组件"],
    evaluationQuestions: ["是否有真实内容结构", "是否能复用到多个项目", "是否保留可访问性", "是否摆脱默认模板味"],
    avoidWhen: ["需求只有装饰效果", "品牌 token 未定义", "组件没有状态和响应式计划"],
  },
  {
    id: "immersive-web-layering",
    title: "沉浸式 Web 层级框架",
    category: "motion",
    sourceIds: ["spline", "codrops", "gsap", "aceternity"],
    coreIdea: "3D、shader 和复杂动效要作为界面层级的一部分，而不是盖住内容的背景玩具。",
    thinkingModel: ["先确定主体任务和可读层", "再定义沉浸层出现位置", "最后定义性能预算和静态 fallback"],
    transferablePatterns: ["3D hero object", "视差产品模型", "局部 shader 背景", "鼠标跟随微视差", "滚动驱动镜头变化"],
    frontendImplementation: ["沉浸层独立懒加载", "首屏文字不依赖 3D 加载", "移动端提供静态海报帧", "监控 LCP/CLS 和 reduced-motion"],
    evaluationQuestions: ["3D 是否解释产品", "是否影响阅读和转化", "是否有降级", "是否限制在高价值区域"],
    avoidWhen: ["后台主流程", "低端设备占比高", "SEO 内容是第一目标", "设计只为了炫技"],
  },
];

export const ADDITIONAL_MATERIAL_ASSETS: MaterialAsset[] = [
  {
    id: "m-gsap-scroll-story",
    patternId: "fx1",
    title: "GSAP 滚动叙事时间线",
    category: "motion",
    sourceId: "gsap",
    mediaKind: "css-motion",
    motionSpec: "用 timeline 管理章节式滚动，视觉元素先出现，解释文本随后 80-140ms 错峰进入。",
    useWhen: ["品牌首屏", "产品能力解释", "案例故事", "需要强记忆点的官网"],
    avoidWhen: ["表格后台", "低性能移动端", "内容需要立即完整可见"],
    designSignals: ["章节感", "节奏明确", "视线被引导", "动画服务叙事"],
    frontendNotes: ["拆成 section timeline", "ScrollTrigger 只绑定高价值区域", "提供 reduced-motion 静态版"],
    tags: ["gsap", "scroll", "timeline", "storytelling"],
    directionFit: ["experimental-premium", "soft-intelligent"],
    recommendationAngle: "适合把产品能力拆成有节奏的视觉故事，而不是一次性堆满功能点。",
    qualityScore: 96,
    examples: ["Awwwards 品牌站滚动叙事", "产品能力章节 reveal"],
    implementationRules: ["timeline 不跨越太多组件边界", "动画参数集中管理", "首屏关键内容 SSR 可读"],
    pitfalls: ["过度 pinning", "滚动距离过长", "移动端动画未降级"],
    previewKind: "particles",
    iconText: "G",
  },
  {
    id: "m-motion-layout-transition",
    patternId: "fx2",
    title: "Motion 布局过渡与共享元素",
    category: "motion",
    sourceId: "motion",
    mediaKind: "css-motion",
    motionSpec: "卡片到详情、tab 切换、筛选重排使用 layout transition，持续 180-320ms。",
    useWhen: ["素材卡片展开", "筛选结果重排", "工作台详情面板", "Agent 推荐刷新"],
    avoidWhen: ["大量虚拟列表", "频繁实时刷新数据", "用户只需要瞬时反馈"],
    designSignals: ["位置变化可追踪", "状态切换自然", "减少认知跳跃"],
    frontendNotes: ["只在少量元素使用 layout", "列表 key 稳定", "动画不改变可访问顺序"],
    tags: ["motion", "react", "layout", "shared-element"],
    directionFit: ["soft-intelligent", "calm-professional"],
    recommendationAngle: "让素材库筛选和详情展开更像一个连续工作台，而不是页面重排。",
    qualityScore: 94,
    implementationRules: ["组件状态先稳定再加动画", "同类卡片使用统一 layoutId 策略", "移动端减少位移距离"],
    pitfalls: ["列表过长性能下降", "动画掩盖加载状态", "key 不稳定导致闪烁"],
    previewKind: "hero",
    iconText: "M",
  },
  {
    id: "m-react-bits-text-effect",
    patternId: "fx3",
    title: "代码化文字动效组件",
    category: "motion",
    sourceId: "react-bits",
    mediaKind: "reference-link",
    motionSpec: "标题、标签、推荐理由使用轻量 reveal，不做逐字炫技，控制在 200-480ms。",
    useWhen: ["Hero 标题", "Agent 生成结果", "素材卡片进入", "空状态引导"],
    avoidWhen: ["长正文", "可访问性要求极高的表单", "密集数据页面"],
    designSignals: ["文字有出现节奏", "不牺牲可读性", "动效组件可复用"],
    frontendNotes: ["文本 SSR 保持可读", "动画层只包裹 display 内容", "screen reader 不重复朗读"],
    tags: ["text-effect", "react", "microinteraction", "headline"],
    directionFit: ["soft-intelligent", "experimental-premium"],
    recommendationAngle: "把文字从静态说明变成有轻微生命力的界面反馈。",
    qualityScore: 88,
    implementationRules: ["优先 opacity + y", "长文本不要逐字动画", "prefers-reduced-motion 直接显示"],
    pitfalls: ["标题像模板特效", "影响阅读速度", "重复动画造成噪音"],
    previewKind: "portfolio",
    iconText: "Rb",
  },
  {
    id: "m-lottie-loading-state",
    patternId: "fx4",
    title: "Lottie 品牌加载与空状态",
    category: "motion",
    sourceId: "lottiefiles",
    mediaKind: "animated-gif",
    motionSpec: "加载和空状态使用短循环矢量动图，单次循环 800-1600ms，避免长时间抢焦点。",
    useWhen: ["AI 分析等待", "素材导入中", "空素材库", "上传完成反馈"],
    avoidWhen: ["主内容区域长时间播放", "无品牌插画系统", "包体积预算很紧"],
    designSignals: ["等待可感知", "品牌亲和", "状态不冰冷"],
    frontendNotes: ["懒加载播放器", "循环次数限制", "失败时显示静态 SVG fallback"],
    tags: ["lottie", "loading", "empty-state", "feedback"],
    directionFit: ["soft-intelligent"],
    recommendationAngle: "适合让 AI 等待过程更有反馈，但必须控制体积和播放范围。",
    qualityScore: 86,
    implementationRules: ["动图资源按需加载", "加载超过 10s 切换为进度说明", "保留静态 fallback"],
    pitfalls: ["动画体积过大", "循环太久", "空状态变成装饰插画"],
    previewKind: "flow",
    iconText: "Lt",
  },
  {
    id: "m-rive-state-machine",
    patternId: "fx5",
    title: "Rive 状态机互动反馈",
    category: "motion",
    sourceId: "rive",
    mediaKind: "video",
    motionSpec: "用状态机绑定 hover、press、success、error，让一个视觉对象响应真实 UI 状态。",
    useWhen: ["品牌 mascot", "按钮反馈", "游戏化 onboarding", "复杂成功/失败反馈"],
    avoidWhen: ["严肃 B2B 后台", "无动效维护能力", "简单 hover 就够的控件"],
    designSignals: ["互动对象有状态", "反馈与操作一致", "动效可被复用"],
    frontendNotes: ["只用于少数高价值互动", "状态输入来自真实业务状态", "加载失败回退静态图"],
    tags: ["rive", "state-machine", "interactive", "feedback"],
    directionFit: ["experimental-premium", "soft-intelligent"],
    recommendationAngle: "适合把品牌互动做成真正响应用户操作的对象，而不是循环播放视频。",
    qualityScore: 85,
    implementationRules: ["状态输入命名和业务状态一致", "不要把所有按钮都 Rive 化", "低端设备关闭复杂效果"],
    pitfalls: ["维护成本高", "状态与业务脱节", "视觉反馈太慢"],
    previewKind: "particles",
    iconText: "Rv",
  },
  {
    id: "m-codrops-creative-transition",
    patternId: "fx6",
    title: "Codrops 创意转场边界",
    category: "motion",
    sourceId: "codrops",
    mediaKind: "reference-link",
    motionSpec: "图像变形、菜单转场、mask reveal 等效果只放在首屏或案例详情入口。",
    useWhen: ["作品集", "创意机构", "品牌 campaign", "高记忆点案例页"],
    avoidWhen: ["后台管理", "转化表单", "性能预算紧张页面"],
    designSignals: ["强记忆点", "实验感", "视觉技术驱动"],
    frontendNotes: ["复杂效果组件隔离", "懒加载重型依赖", "不阻塞主要 CTA"],
    tags: ["creative-coding", "transition", "webgl", "mask"],
    directionFit: ["experimental-premium"],
    recommendationAngle: "适合建立强烈视觉识别，但必须被产品目标约束。",
    qualityScore: 87,
    implementationRules: ["CSS mask 可解决就不用 WebGL", "效果区独立渲染", "保留静态海报帧"],
    pitfalls: ["技术炫技盖过内容", "LCP 变差", "移动端不可用"],
    previewKind: "portfolio",
    iconText: "Cd",
  },
  {
    id: "m-typewolf-font-moodboard",
    patternId: "ty1",
    title: "Typewolf 字体情绪板",
    category: "typography",
    sourceId: "typewolf",
    mediaKind: "reference-link",
    motionSpec: "字体预览切换只做 160ms opacity，避免文字排版跳动。",
    useWhen: ["品牌官网", "作品集", "高端 SaaS", "需要摆脱模板感的首屏"],
    avoidWhen: ["字体授权不清", "中文内容占比极高但只选英文字体", "性能预算很低"],
    designSignals: ["字体有情绪", "标题和正文角色清楚", "品牌气质由文字建立"],
    frontendNotes: ["标题字体和正文字体分离", "字体加载策略明确", "fallback 尺寸接近"],
    tags: ["typography", "font-pairing", "brand", "moodboard"],
    directionFit: ["experimental-premium", "calm-professional"],
    recommendationAngle: "帮助从字体气质出发定义页面，而不是只靠颜色和卡片。",
    qualityScore: 93,
    implementationRules: ["限制字体文件数量", "font-display: swap 或 optional", "中文 fallback 单独校准"],
    pitfalls: ["英文字体套中文", "字体太多", "标题好看但正文难读"],
    previewKind: "portfolio",
    iconText: "Tw",
  },
  {
    id: "m-fonts-in-use-role-map",
    patternId: "ty2",
    title: "真实品牌字体角色映射",
    category: "typography",
    sourceId: "fonts-in-use",
    mediaKind: "static-image",
    motionSpec: "字体案例对比不做动效，重点展示标题、正文、标签、数字的角色差异。",
    useWhen: ["设计系统", "品牌改版", "中英混排", "营销站信息层级"],
    avoidWhen: ["没有品牌定位", "只需要系统默认字体", "无法确定授权"],
    designSignals: ["角色分工", "品牌一致", "真实案例支撑"],
    frontendNotes: ["建立 type role token", "用样例句测试中英文", "数字和表格单独检查"],
    tags: ["font-role", "case-study", "brand", "typography"],
    directionFit: ["calm-professional", "experimental-premium"],
    recommendationAngle: "把字体选择从审美偏好变成可解释的角色系统。",
    qualityScore: 91,
    implementationRules: ["定义 display/title/body/label/code 五类 token", "按钮文字不继承正文", "中英文样例同时验收"],
    pitfalls: ["只看海报不看 UI", "忽略授权", "fallback 后高度变化"],
    previewKind: "hero",
    iconText: "Fi",
  },
  {
    id: "m-google-variable-fonts",
    patternId: "ty3",
    title: "变量字体性能与层级",
    category: "typography",
    sourceId: "google-fonts",
    mediaKind: "reference-link",
    motionSpec: "字体粗细变化用于 hover 或重点强调时控制在 100-180ms，避免整段文字跳动。",
    useWhen: ["多层级文档", "工具界面", "国际化页面", "需要减小字体文件数"],
    avoidWhen: ["浏览器兼容要求极旧", "字体轴不稳定", "中文字体体积过大"],
    designSignals: ["可变字重", "加载可控", "跨平台稳定"],
    frontendNotes: ["subset 和 preload", "font metric fallback", "避免运行时频繁改变 font-weight"],
    tags: ["variable-font", "performance", "webfont", "typography"],
    directionFit: ["calm-professional", "soft-intelligent"],
    recommendationAngle: "适合用一个字体文件覆盖多个层级，同时控制性能。",
    qualityScore: 86,
    implementationRules: ["只加载需要的字重/字符集", "关键字体 preload", "正文 fallback 不跳版"],
    pitfalls: ["字体闪烁", "中文包体过大", "变量轴滥用"],
    previewKind: "hero",
    iconText: "Gf",
  },
  {
    id: "m-shadcn-composable-system",
    patternId: "ui1",
    title: "shadcn 可组合组件系统",
    category: "ui",
    sourceId: "shadcn-ui",
    mediaKind: "reference-link",
    motionSpec: "组件状态反馈保持克制，focus/hover/selected 使用 120-180ms 过渡。",
    useWhen: ["后台工具", "AI 工作台", "设置页", "表单密集产品"],
    avoidWhen: ["强品牌视觉页", "完全自定义艺术方向", "无需可访问组件的静态页面"],
    designSignals: ["组件可复制", "token 清晰", "表单和弹窗规范", "工程可维护"],
    frontendNotes: ["使用 primitive + variant", "主题 token 集中", "表单错误态标准化"],
    tags: ["component-system", "react", "dashboard", "forms"],
    directionFit: ["calm-professional", "soft-intelligent"],
    recommendationAngle: "适合把素材库从 demo UI 推向真实工具组件体系。",
    qualityScore: 95,
    implementationRules: ["抽出 Button/Card/Tabs/Dialog primitives", "variants 不散落在页面", "focus-visible 必须可见"],
    pitfalls: ["默认样式太像模板", "组件嵌套过深", "没有品牌 token"],
    previewKind: "flow",
    iconText: "Sc",
  },
  {
    id: "m-radix-accessible-interaction",
    patternId: "ui2",
    title: "Radix 可访问交互骨架",
    category: "ui",
    sourceId: "radix-ui",
    mediaKind: "reference-link",
    motionSpec: "弹窗、菜单、popover 入场 120-180ms，退出更快，焦点回到触发器。",
    useWhen: ["筛选菜单", "素材详情弹窗", "命令菜单", "收藏/导出操作"],
    avoidWhen: ["只需要静态链接", "自定义交互无法维护焦点", "移动端应使用原生 sheet"],
    designSignals: ["键盘可用", "焦点稳定", "语义正确", "行为可预期"],
    frontendNotes: ["用 headless primitive", "样式和行为分离", "escape/blur/焦点陷阱完整"],
    tags: ["accessibility", "dialog", "popover", "menu"],
    directionFit: ["calm-professional", "soft-intelligent"],
    recommendationAngle: "让素材库的高级交互不牺牲可访问性和稳定性。",
    qualityScore: 94,
    implementationRules: ["不要手写复杂弹窗行为", "所有菜单支持键盘", "关闭后恢复焦点"],
    pitfalls: ["只做视觉弹窗", "焦点丢失", "移动端遮挡输入"],
    previewKind: "flow",
    iconText: "Rx",
  },
  {
    id: "m-linear-command-density",
    patternId: "ui3",
    title: "Linear 式命令密度",
    category: "ui",
    sourceId: "linear",
    mediaKind: "static-image",
    motionSpec: "高频操作反馈低噪音，hover/selected 只改变背景和边框，保持 120ms 内响应。",
    useWhen: ["项目管理", "素材库管理", "Agent 历史", "高频筛选和收藏"],
    avoidWhen: ["营销首页", "儿童产品", "强插画风格"],
    designSignals: ["低噪音", "键盘优先", "高信息密度", "操作路径短"],
    frontendNotes: ["命令入口统一", "列表和快捷键优先", "状态色克制"],
    tags: ["product-ui", "command", "density", "saas"],
    directionFit: ["calm-professional"],
    recommendationAngle: "适合把素材库做成专业工具，而不是漂亮但低效的展示页。",
    qualityScore: 92,
    implementationRules: ["历史/收藏/筛选提供命令入口", "列表项高度稳定", "键盘快捷键可发现"],
    pitfalls: ["过度隐藏操作", "新用户不可发现", "密度太高牺牲阅读"],
    previewKind: "phones",
    iconText: "Ln",
  },
  {
    id: "m-material-color-roles",
    patternId: "co1",
    title: "Material 3 语义色彩角色",
    category: "color",
    sourceId: "material-design",
    mediaKind: "reference-link",
    motionSpec: "色彩状态变化只使用 120-180ms 过渡，避免大面积背景突然跳变。",
    useWhen: ["设计系统", "SaaS 工作台", "需要浅深色模式", "状态色很多的产品"],
    avoidWhen: ["一次性活动页", "已有不可变品牌手册", "只靠渐变营造高级感"],
    designSignals: ["颜色有角色", "状态可区分", "对比度稳定", "暗色模式可扩展"],
    frontendNotes: ["定义 background/surface/primary/secondary/error/outline token", "组件只消费语义 token", "状态色不复用品牌色"],
    tags: ["color-token", "design-system", "material", "accessibility"],
    directionFit: ["calm-professional", "soft-intelligent"],
    recommendationAngle: "适合把配色从灵感图升级成可维护的产品色彩系统。",
    qualityScore: 94,
    examples: ["Material 3 role-based colors", "后台工具浅深色主题"],
    implementationRules: ["CSS variables 按语义命名", "文字和按钮状态检查对比度", "深色模式单独校准不是自动反色"],
    pitfalls: ["把主色用到所有地方", "状态色和品牌色冲突", "渐变压低文字可读性"],
    recommendedFor: ["长期维护产品", "多页面工具", "有主题切换需求的项目"],
    previewKind: "palette",
    iconText: "M3",
  },
  {
    id: "m-huemint-brand-intersection",
    patternId: "co2",
    title: "Huemint 品牌交叉配色",
    category: "color",
    sourceId: "huemint",
    mediaKind: "static-image",
    motionSpec: "配色预览切换时保持色块位置稳定，只切换 token 值。",
    useWhen: ["新品牌官网", "AI 产品首屏", "需要同时专业和有记忆点", "多套视觉方向比选"],
    avoidWhen: ["品牌色已严格锁定", "行业有强合规颜色", "页面信息架构还没定"],
    designSignals: ["主辅色关系清楚", "背景与强调分离", "品牌色不抢正文", "色彩有情绪但不花"],
    frontendNotes: ["先定中性色和正文色", "品牌色只用于 CTA/选中/关键图形", "辅助色控制在少量模块"],
    tags: ["palette", "brand", "contrast", "ai-product"],
    directionFit: ["soft-intelligent", "experimental-premium"],
    recommendationAngle: "适合为 AI 产品快速生成几套可讨论的品牌色彩方向。",
    qualityScore: 90,
    implementationRules: ["每套 palette 输出 8-12 个 token", "正文色优先于品牌色", "色块预览包含浅/深/状态样本"],
    pitfalls: ["只选好看的色块", "没有文本对比测试", "辅助色过多导致页面碎"],
    previewKind: "palette",
    iconText: "Hm",
  },
  {
    id: "m-apple-hig-navigation",
    patternId: "la1",
    title: "Apple HIG 导航层级",
    category: "layout",
    sourceId: "apple-hig",
    mediaKind: "reference-link",
    motionSpec: "层级推进使用方向明确的过渡，返回动作比进入更快，避免迷失。",
    useWhen: ["Mac/iOS 风格工具", "设置页", "详情页层级", "移动端素材库"],
    avoidWhen: ["强实验性作品集", "单页营销站", "不需要平台一致性的活动页"],
    designSignals: ["层级清楚", "返回路径可见", "当前上下文稳定", "控件行为符合平台习惯"],
    frontendNotes: ["桌面使用 sidebar + detail", "移动端使用 stack navigation", "面包屑/返回按钮保持一致"],
    tags: ["navigation", "layout", "platform", "hierarchy"],
    directionFit: ["calm-professional", "soft-intelligent"],
    recommendationAngle: "适合把素材库和 Agent 工作台整理成清晰的产品层级。",
    qualityScore: 91,
    implementationRules: ["主导航不超过 5-7 个入口", "详情页保留回到列表路径", "移动端避免三栏硬塞"],
    pitfalls: ["导航入口重复", "详情面板没有上下文", "移动端返回路径丢失"],
    previewKind: "flow",
    iconText: "HIG",
  },
  {
    id: "m-mobbin-mobile-density",
    patternId: "la2",
    title: "Mobbin 移动端信息密度",
    category: "layout",
    sourceId: "mobbin",
    mediaKind: "static-image",
    motionSpec: "列表刷新和筛选只做轻微 opacity/translate，避免移动端大面积跳动。",
    useWhen: ["移动端工作流", "素材列表", "收藏夹", "搜索结果", "项目历史"],
    avoidWhen: ["图片主导的画廊", "沉浸式视觉首页", "内容极少的单屏工具"],
    designSignals: ["扫读效率", "触控目标稳定", "信息分组清楚", "状态和操作不混乱"],
    frontendNotes: ["列表项高度稳定", "主操作放右侧或底部", "筛选条件以 chip 展示并可撤销"],
    tags: ["mobile-ui", "density", "list", "filters"],
    directionFit: ["calm-professional"],
    recommendationAngle: "适合把桌面素材库迁移到移动端时保持可用性。",
    qualityScore: 89,
    implementationRules: ["触控目标至少 44px", "长标题两行截断", "筛选结果数量可见"],
    pitfalls: ["卡片太高导致扫读慢", "图标无标签", "筛选状态不可见"],
    previewKind: "phones",
    iconText: "Mb",
  },
  {
    id: "m-pageflows-state-audit",
    patternId: "ui4",
    title: "Pageflows 状态路径审计",
    category: "ui",
    sourceId: "pageflows",
    mediaKind: "reference-link",
    motionSpec: "每个流程状态切换都给出即时反馈，loading 不超过 400ms 才显示骨架屏。",
    useWhen: ["Onboarding", "AI 生成流程", "上传/导入", "设置保存", "支付或提交"],
    avoidWhen: ["纯静态内容页", "没有明确流程的灵感墙", "单次点击无异步状态"],
    designSignals: ["流程完整", "状态不丢", "错误可恢复", "成功反馈明确"],
    frontendNotes: ["为 empty/loading/success/error/partial 写组件", "失败态提供重试和原因", "成功态给下一步"],
    tags: ["interaction-flow", "states", "feedback", "audit"],
    directionFit: ["soft-intelligent", "calm-professional"],
    recommendationAngle: "让 Agent 推荐从卡片展示升级为完整工作流体验。",
    qualityScore: 93,
    implementationRules: ["每个异步动作至少三态", "错误信息靠近操作源", "成功后不要只 toast"],
    pitfalls: ["只有 happy path", "loading 过早闪烁", "错误只能刷新页面解决"],
    previewKind: "flow",
    iconText: "Pf",
  },
  {
    id: "m-v0-component-blueprint",
    patternId: "ui5",
    title: "v0 组件蓝图拆解",
    category: "ui",
    sourceId: "v0",
    mediaKind: "reference-link",
    motionSpec: "组件交互动效优先用 CSS transition，避免模板组件堆叠后性能变差。",
    useWhen: ["快速生成前端初稿", "组件结构参考", "后台工具", "AI 输出转代码"],
    avoidWhen: ["需要独特品牌表达的首屏", "未做产品结构判断", "直接复制模板不改信息架构"],
    designSignals: ["结构清晰", "组件可复用", "状态完整", "可快速落地"],
    frontendNotes: ["先抽象布局和组件关系", "再改品牌 token 和内容", "保留可访问属性和状态"],
    tags: ["template", "component", "nextjs", "blueprint"],
    directionFit: ["calm-professional", "soft-intelligent"],
    recommendationAngle: "适合把 Agent 输出变成可执行的 React/Next 组件计划。",
    qualityScore: 90,
    implementationRules: ["模板只迁移结构不迁移默认审美", "组件 props 明确", "重复区块抽成 data-driven"],
    pitfalls: ["页面像模板站", "组件命名混乱", "没有真实状态"],
    previewKind: "hero",
    iconText: "v0",
  },
  {
    id: "m-nngroup-heuristic-check",
    patternId: "ui6",
    title: "NN/g 可用性启发式检查",
    category: "ui",
    sourceId: "nngroup",
    mediaKind: "reference-link",
    motionSpec: "反馈动效只在用户需要确认状态时出现，避免干扰识别和控制。",
    useWhen: ["产品可用性验收", "复杂表单", "设置页", "Agent 推荐流程", "素材检索"],
    avoidWhen: ["纯视觉探索阶段", "没有具体任务路径", "只追求情绪氛围"],
    designSignals: ["状态可见", "匹配用户语言", "控制感", "错误预防", "一致性"],
    frontendNotes: ["所有操作有反馈", "术语使用用户语言", "危险操作二次确认", "撤销/重试路径可见"],
    tags: ["ux", "heuristics", "usability", "workflow"],
    directionFit: ["calm-professional"],
    recommendationAngle: "把灵感推荐后的执行方案用可用性规则再过滤一遍。",
    qualityScore: 92,
    implementationRules: ["写入验收 checklist", "错误态和空态纳入组件库", "高风险操作支持撤销"],
    pitfalls: ["只看美观不看任务", "反馈只靠 toast", "用户无法恢复错误"],
    previewKind: "flow",
    iconText: "NN",
  },
  {
    id: "m-awwwards-portfolio-rhythm",
    patternId: "la3",
    title: "Awwwards 作品集页面节奏",
    category: "layout",
    sourceId: "awwwards",
    mediaKind: "video",
    motionSpec: "作品集滚动节奏使用大图、短文案和局部转场，避免每屏都是相同卡片网格。",
    useWhen: ["作品集", "品牌案例", "创意机构官网", "产品发布页"],
    avoidWhen: ["后台工具", "高转化表单", "内容需要快速比较"],
    designSignals: ["章节节奏", "视觉记忆点", "空间留白", "案例之间有变化"],
    frontendNotes: ["每个 section 定义不同图文比例", "首屏必须露出下一屏线索", "媒体保持稳定 aspect-ratio"],
    tags: ["portfolio", "rhythm", "case-study", "visual-story"],
    directionFit: ["experimental-premium"],
    recommendationAngle: "适合让品牌页摆脱重复卡片堆叠，建立作品级节奏。",
    qualityScore: 91,
    implementationRules: ["至少设计 3 种 section 节奏", "媒体加载前保留尺寸", "滚动动效不抢 CTA"],
    pitfalls: ["只模仿夸张动效", "信息被图片压住", "移动端变成长图堆叠"],
    previewKind: "portfolio",
    iconText: "Aw",
  },
  {
    id: "m-baymard-form-recovery",
    patternId: "ui7",
    title: "Baymard 表单错误恢复",
    category: "ui",
    sourceId: "baymard",
    mediaKind: "reference-link",
    motionSpec: "错误出现用轻微 highlight 和位置保持，不要让表单跳动或把焦点带离字段。",
    useWhen: ["注册", "结账", "设置保存", "API Key 配置", "素材导入表单"],
    avoidWhen: ["无输入流程", "一次性静态展示", "错误不会影响任务完成"],
    designSignals: ["错误靠近字段", "原因可理解", "恢复路径明确", "输入负担低"],
    frontendNotes: ["字段级错误优先于全局 toast", "保留用户已输入内容", "复杂输入提供格式示例"],
    tags: ["form", "error", "conversion", "recovery"],
    directionFit: ["calm-professional"],
    recommendationAngle: "适合让真实产品流程少掉 demo 常见的表单失败体验。",
    qualityScore: 90,
    implementationRules: ["错误文本紧贴字段", "提交失败不清空输入", "第一处错误自动聚焦但不滚动失控"],
    pitfalls: ["只有顶部错误提示", "错误文案像系统异常", "用户不知道怎么改"],
    previewKind: "flow",
    iconText: "By",
  },
  {
    id: "m-magic-ui-animated-hero",
    patternId: "ui8",
    title: "Magic UI 动效 Hero 组件",
    category: "motion",
    sourceId: "magic-ui",
    mediaKind: "css-motion",
    motionSpec: "用光效、文字 reveal、背景网格和细粒度 motion 组合首屏，动画控制在内容出现之后。",
    useWhen: ["AI 产品官网", "开发者工具 landing", "需要快速建立科技感", "首屏需要记忆点"],
    avoidWhen: ["后台主工作流", "文字信息很多的首屏", "品牌需要极度克制"],
    designSignals: ["React/Tailwind/Motion 可复制", "首屏氛围强", "组件化边界清楚", "适合 shadcn 体系"],
    frontendNotes: ["将背景动效、标题动效、CTA 分组件", "默认提供 reduced-motion", "动画不阻塞主标题渲染"],
    tags: ["magic-ui", "hero", "motion", "landing"],
    directionFit: ["soft-intelligent", "experimental-premium"],
    recommendationAngle: "适合把 AI 产品首屏做得更有生命力，同时保持代码组件化。",
    qualityScore: 94,
    examples: ["Kinetic Text", "Animated Grid Background", "Landing page hero blocks"],
    implementationRules: ["动效组件不能包住整页", "关键文案 SSR 可见", "光效透明度控制在背景层"],
    pitfalls: ["过度堆动效", "默认模板味太重", "移动端背景影响性能"],
    previewKind: "particles",
    iconText: "Mu",
  },
  {
    id: "m-aceternity-premium-blocks",
    patternId: "ui9",
    title: "Aceternity 高级视觉组件块",
    category: "ui",
    sourceId: "aceternity",
    mediaKind: "reference-link",
    motionSpec: "Hero、Bento、Parallax、Glare、Canvas、Text Reveal 等组件用 180-520ms 的局部动效强化记忆点。",
    useWhen: ["SaaS 官网", "创意产品页", "功能区块", "展示型 dashboard 入口"],
    avoidWhen: ["强表单流程", "需要极低认知负担", "没有品牌 token 的快速拼装"],
    designSignals: ["高级组件块", "Tailwind + Motion", "强视觉记忆", "可复制但需改造"],
    frontendNotes: ["先抽象内容模型", "组件块只服务一个区块目标", "复制后替换默认 token 和 copy"],
    tags: ["aceternity", "bento", "parallax", "premium-ui"],
    directionFit: ["experimental-premium", "soft-intelligent"],
    recommendationAngle: "适合把普通功能区变成有记忆点的高级视觉模块。",
    qualityScore: 93,
    examples: ["Bento Grids", "Glare Card", "Text Reveal Card", "Globe"],
    implementationRules: ["组件块不要直接堆叠", "同页最多 1-2 个强特效", "保留静态 fallback"],
    pitfalls: ["视觉强但信息弱", "多个特效互抢焦点", "复制后不可维护"],
    previewKind: "portfolio",
    iconText: "Ac",
  },
  {
    id: "m-21st-component-search-map",
    patternId: "ui10",
    title: "21st.dev 组件检索分类地图",
    category: "ui",
    sourceId: "twenty-first",
    mediaKind: "reference-link",
    motionSpec: "组件库检索本身不需要强动画，重点是分类、过滤、命令搜索和结果可比较。",
    useWhen: ["组件素材库", "模板市场", "Agent 生成组件推荐", "前端资源导航"],
    avoidWhen: ["只展示少量精选案例", "不需要检索的营销页", "分类还没有整理好"],
    designSignals: ["模块分类非常细", "模板和组件分层", "搜索优先", "适合 Agent 检索"],
    frontendNotes: ["给每个素材打 category/source/media/scene 标签", "搜索结果支持直接跳详情", "保留收藏和复制入口"],
    tags: ["component-search", "templates", "ai-chat", "library"],
    directionFit: ["calm-professional", "soft-intelligent"],
    recommendationAngle: "适合参考它的分类法来整理我们的素材库，而不是只按视觉风格堆卡片。",
    qualityScore: 92,
    examples: ["Heroes", "AI Chats", "Pricing", "Cards", "Navigation"],
    implementationRules: ["分类维度可组合", "搜索字段包含适用场景和避坑", "结果卡片必须可比较"],
    pitfalls: ["分类过多没有优先级", "搜索只搜标题", "模板和素材混在一起"],
    previewKind: "flow",
    iconText: "21",
  },
  {
    id: "m-animata-accessible-motion",
    patternId: "fx7",
    title: "Animata 可访问动效组件",
    category: "motion",
    sourceId: "animata",
    mediaKind: "css-motion",
    motionSpec: "可复制动画组件强调 focus、screen reader、reduced-motion 和真实产品场景，避免纯展示动效。",
    useWhen: ["按钮动效", "Skeleton", "Tabs", "Scroll reveal", "Preloader", "图表/列表反馈"],
    avoidWhen: ["只需要静态排版", "设备性能不可控", "动效会抢正文注意力"],
    designSignals: ["开源动画组件", "可访问性前置", "真实产品来源", "跨框架可迁移"],
    frontendNotes: ["复制前保留 aria/focus/reduced-motion", "动画参数抽 token", "组件级测试 hover/focus/keyboard"],
    tags: ["animata", "accessible-motion", "components", "reduced-motion"],
    directionFit: ["calm-professional", "soft-intelligent"],
    recommendationAngle: "适合把动效素材做成可靠组件，而不是一次性视觉效果。",
    qualityScore: 91,
    examples: ["Skeleton", "Scroll", "Tabs", "Text", "Progress"],
    implementationRules: ["所有动效有禁用路径", "优先 transform/opacity", "避免改变布局尺寸"],
    pitfalls: ["忽略键盘焦点", "组件只在 hover 下好看", "复制后丢失可访问性"],
    previewKind: "flow",
    iconText: "An",
  },
  {
    id: "m-hover-dev-microinteractions",
    patternId: "fx8",
    title: "Hover.dev 微交互模板",
    category: "motion",
    sourceId: "hover-dev",
    mediaKind: "css-motion",
    motionSpec: "hover、press、cursor、card tilt 和 text reveal 用 80-220ms 反馈强化可点击性。",
    useWhen: ["素材卡片 hover", "CTA 按钮", "导航项", "作品集缩略图", "交互式 demo"],
    avoidWhen: ["触屏端主要用户", "表格高频操作", "状态反馈需要明确文字"],
    designSignals: ["局部微交互", "点击性增强", "手感细节", "轻量可复制"],
    frontendNotes: ["hover 不改变布局", "移动端转为 tap/focus 状态", "同一页面只用一种 hover 语言"],
    tags: ["hover", "microinteraction", "button", "card"],
    directionFit: ["soft-intelligent", "experimental-premium"],
    recommendationAngle: "适合给素材库和官网增加细腻手感，但不能让交互变成噪音。",
    qualityScore: 88,
    examples: ["Hover cards", "Cursor effects", "Button interactions", "Text reveal"],
    implementationRules: ["hover 只改 transform/opacity/border", "focus-visible 与 hover 对齐", "触屏降级"],
    pitfalls: ["hover 造成布局抖动", "触屏无反馈", "不同卡片动效不统一"],
    previewKind: "hero",
    iconText: "Hv",
  },
  {
    id: "m-uiverse-small-ui-elements",
    patternId: "ui11",
    title: "Uiverse 小型 UI 元素状态库",
    category: "ui",
    sourceId: "uiverse",
    mediaKind: "reference-link",
    motionSpec: "按钮、加载器、切换器、卡片等小元素用短反馈表达 hover/active/loading/disabled。",
    useWhen: ["按钮状态", "loading 反馈", "表单控件", "开关切换", "实验性 UI 小组件"],
    avoidWhen: ["需要完整设计系统", "品牌一致性要求很高", "组件代码质量未经审查"],
    designSignals: ["小组件丰富", "状态变化多", "CSS 创意强", "适合灵感采样"],
    frontendNotes: ["只迁移状态思想，不直接复制未知代码", "统一到项目 token", "组件必须补充 aria 和禁用态"],
    tags: ["uiverse", "buttons", "loaders", "forms", "css"],
    directionFit: ["experimental-premium", "soft-intelligent"],
    recommendationAngle: "适合补充按钮、加载、切换器等局部细节灵感。",
    qualityScore: 84,
    examples: ["Buttons", "Loaders", "Switches", "Cards", "Forms"],
    implementationRules: ["代码先审查再迁移", "视觉统一到项目 token", "状态语义不能只靠颜色"],
    pitfalls: ["代码质量参差", "视觉风格不统一", "小组件堆叠导致产品碎片化"],
    previewKind: "hero",
    iconText: "Ui",
  },
  {
    id: "m-spline-3d-product-hero",
    patternId: "fx9",
    title: "Spline 3D 产品 Hero 场景",
    category: "motion",
    sourceId: "spline",
    mediaKind: "video",
    motionSpec: "3D 产品物体作为首屏辅助层，默认静态可见，鼠标/滚动只做轻微视差和镜头变化。",
    useWhen: ["AI 硬件/软件品牌", "产品发布页", "创意官网", "需要强记忆点的首屏"],
    avoidWhen: ["内容 SEO 优先", "低端移动设备", "用户要快速完成任务", "没有静态 fallback"],
    designSignals: ["浏览器 3D", "实时交互", "产品物体记忆点", "沉浸式但需克制"],
    frontendNotes: ["3D iframe/运行时懒加载", "首屏文本不依赖 3D", "移动端使用 poster fallback", "限制帧率和交互范围"],
    tags: ["spline", "3d", "hero", "webgl"],
    directionFit: ["experimental-premium"],
    recommendationAngle: "适合用 3D 建立品牌记忆点，但必须有性能预算和降级方案。",
    qualityScore: 89,
    examples: ["3D product hero", "Interactive object", "Scroll camera shift"],
    implementationRules: ["先加载文本和 CTA", "3D 层延迟加载", "静态 fallback 必须存在"],
    pitfalls: ["3D 盖住内容", "首屏性能变差", "移动端不可用"],
    previewKind: "particles",
    iconText: "Sp",
  },
];

export function buildDesignKnowledgeContext(): string {
  const frameworks = DESIGN_FRAMEWORKS.map((framework) => [
    `FRAMEWORK ${framework.id}: ${framework.title}`,
    `category=${framework.category}`,
    `sources=${framework.sourceIds.join(",")}`,
    `core=${framework.coreIdea}`,
    `thinking=${framework.thinkingModel.join("；")}`,
    `patterns=${framework.transferablePatterns.join("、")}`,
    `frontend=${framework.frontendImplementation.join("；")}`,
    `evaluate=${framework.evaluationQuestions.join("、")}`,
  ].join(" | ")).join("\n");

  const sources = ADDITIONAL_MATERIAL_SOURCES.map((source) => [
    `SOURCE ${source.id}: ${source.name}`,
    `kind=${source.kind}`,
    `signal=${source.signal}`,
    `note=${source.note}`,
    `href=${source.href}`,
  ].join(" | ")).join("\n");

  return `${frameworks}\n\n${sources}`;
}
