import type { MaterialAsset, MaterialSource } from "@/lib/types";

export const MATERIAL_SOURCES: MaterialSource[] = [
  {
    id: "pageflows",
    name: "Pageflows",
    href: "https://pageflows.com/",
    kind: "interaction-flow",
    signal: "流程拆解",
    note: "用于判断 onboarding、checkout、dashboard、表单和状态反馈是否完整。",
  },
  {
    id: "mobbin",
    name: "Mobbin",
    href: "https://mobbin.com/discover/apps/ios/latest",
    kind: "product-ui",
    signal: "真实 App 截图库",
    note: "用于校准移动端信息密度、列表结构、导航层级和控件状态。",
  },
  {
    id: "godly",
    name: "Godly",
    href: "https://godly.website/",
    kind: "website-inspiration",
    signal: "新鲜网页灵感",
    note: "用于捕捉 AI 工具、SaaS、创意网站中的新式首屏和动效表达。",
  },
  {
    id: "v0",
    name: "v0 Templates",
    href: "https://v0.app/templates",
    kind: "template",
    signal: "可执行组件结构",
    note: "用于把设计方向翻译成可落地的 React/Next 组件组合。",
  },
  {
    id: "awwwards",
    name: "Awwwards",
    href: "https://www.awwwards.com/websites/portfolio/",
    kind: "website-inspiration",
    signal: "高级视觉完成度",
    note: "用于判断作品集和品牌站的节奏、记忆点和非模板感。",
  },
  {
    id: "huemint",
    name: "Huemint",
    href: "https://huemint.com/brand-intersection/",
    kind: "color-system",
    signal: "品牌配色关系",
    note: "用于生成主色、辅助色、背景色和可读性之间的约束。",
  },
];

export const MATERIAL_ASSETS: MaterialAsset[] = [
  {
    id: "m-space-scroll",
    patternId: "p1",
    title: "留白驱动的滚动呼吸感",
    sourceId: "awwwards",
    mediaKind: "css-motion",
    motionSpec: "大块留白配合 280ms fade-up，滚动进入时只移动 24-40px，不做夸张缩放。",
    useWhen: ["高客单价产品", "作品集", "需要建立信任的 SaaS 首屏"],
    avoidWhen: ["信息极密集的后台", "需要快速比较大量数据的页面"],
    designSignals: ["单视口单焦点", "大标题低噪音", "区块之间形成停顿"],
    frontendNotes: ["使用 IntersectionObserver", "section padding 72-120px", "优先控制 max-width 而不是塞卡片"],
    tags: ["landing", "premium", "scroll", "quiet"],
    directionFit: ["calm-professional", "experimental-premium"],
  },
  {
    id: "m-asymmetric-rail",
    patternId: "p2",
    title: "非对称素材轨道",
    sourceId: "godly",
    mediaKind: "animated-gif",
    motionSpec: "左右错位的图片或组件轨道缓慢漂移，hover 时局部暂停并显示说明。",
    useWhen: ["创意机构", "AI 产品展示", "作品集案例墙"],
    avoidWhen: ["法律金融页面", "强转化表单页"],
    designSignals: ["错位网格", "图片尺寸有主次", "滚动时保持版式张力"],
    frontendNotes: ["CSS grid-template-areas", "aspect-ratio 固定素材容器", "hover pause animation"],
    tags: ["gallery", "portfolio", "motion", "editorial"],
    directionFit: ["experimental-premium", "soft-intelligent"],
  },
  {
    id: "m-card-stack-demo",
    patternId: "p3",
    title: "可展开的卡片堆叠演示",
    sourceId: "v0",
    mediaKind: "css-motion",
    motionSpec: "卡片 hover 上浮 6px，选中后展开为详情，后台卡片保持 8-12px 可见边缘。",
    useWhen: ["功能对比", "多方案选择", "案例摘要"],
    avoidWhen: ["严肃长文", "需要同时展示全部信息的表格"],
    designSignals: ["层叠关系", "前后景深", "点击后状态明确"],
    frontendNotes: ["framer-motion layout", "aria-expanded", "移动端改为纵向 accordion"],
    tags: ["cards", "compare", "stateful", "microinteraction"],
    directionFit: ["soft-intelligent", "calm-professional"],
  },
  {
    id: "m-duotone-console",
    patternId: "p4",
    title: "双色层级控制台",
    sourceId: "mobbin",
    mediaKind: "video",
    motionSpec: "层级变化只改变明度，选中/聚焦用单一强调色，数据刷新时做轻微 shimmer。",
    useWhen: ["开发者工具", "AI 工作台", "数据面板"],
    avoidWhen: ["生活方式品牌", "儿童或强情绪产品"],
    designSignals: ["层级靠明度", "强调色克制", "状态反馈一致"],
    frontendNotes: ["定义 elevation token", "focus-visible 明确", "loading skeleton 不改变布局"],
    tags: ["dashboard", "developer", "dark-mode", "state"],
    directionFit: ["calm-professional", "soft-intelligent"],
  },
  {
    id: "m-color-chapters",
    patternId: "p5",
    title: "色块章节叙事",
    sourceId: "huemint",
    mediaKind: "static-image",
    motionSpec: "章节切换时背景色通过 420ms 低对比渐变过渡，吸顶导航同步切换当前章节标记。",
    useWhen: ["品牌故事", "功能分层叙事", "服务介绍页"],
    avoidWhen: ["单一任务工具页", "需要极强专业克制的 B2B 页面"],
    designSignals: ["章节色彩有秩序", "相邻颜色不过度跳变", "文字对比稳定"],
    frontendNotes: ["CSS custom properties per section", "sticky progress nav", "contrast token 检查"],
    tags: ["brand", "color", "storytelling", "sections"],
    directionFit: ["soft-intelligent", "experimental-premium"],
  },
  {
    id: "m-muted-gradient-media",
    patternId: "p6",
    title: "柔和渐变媒体层",
    sourceId: "godly",
    mediaKind: "animated-gif",
    motionSpec: "渐变背景以 8-12s 慢速移动，前景内容不跟随漂移，避免廉价炫光。",
    useWhen: ["AI 产品首屏", "视觉化能力解释", "图片上叠文字"],
    avoidWhen: ["已有复杂截图背景", "需要纯白高可信界面"],
    designSignals: ["低透明度渐变", "文字可读", "不抢主体"],
    frontendNotes: ["background-size 160%", "prefers-reduced-motion", "叠层透明度 10-24%"],
    tags: ["hero", "gradient", "ai", "atmosphere"],
    directionFit: ["soft-intelligent", "experimental-premium"],
  },
  {
    id: "m-type-scale",
    patternId: "p7",
    title: "字号对比节奏",
    sourceId: "awwwards",
    mediaKind: "static-image",
    motionSpec: "大标题入场只做 opacity 和 16px 位移，避免文字缩放造成 AI 模板味。",
    useWhen: ["强主张首屏", "价格锚点", "关键卖点"],
    avoidWhen: ["大量正文阅读", "需要极小屏密度的移动工具"],
    designSignals: ["标题和正文差距明确", "字重层级清楚", "周围有留白"],
    frontendNotes: ["clamp 控制标题", "按钮文字单独定义 size", "避免负字距"],
    tags: ["typography", "hero", "hierarchy", "copy"],
    directionFit: ["calm-professional", "experimental-premium"],
  },
  {
    id: "m-bilingual-type",
    patternId: "p8",
    title: "中英混排层级",
    sourceId: "mobbin",
    mediaKind: "reference-link",
    motionSpec: "语言切换时保持布局尺寸稳定，只做 160ms opacity 过渡。",
    useWhen: ["国际品牌", "双语产品", "面向海外用户的中文团队"],
    avoidWhen: ["单语言强转化页", "字体资源受限的低端设备"],
    designSignals: ["中英文角色分工", "行高匹配", "切换不跳版"],
    frontendNotes: ["locale copy 长度预算", "font fallback 明确", "按钮宽度使用 min-width"],
    tags: ["i18n", "typography", "brand", "global"],
    directionFit: ["calm-professional", "experimental-premium"],
  },
  {
    id: "m-magnetic-cta",
    patternId: "p9",
    title: "磁吸 CTA 微交互",
    sourceId: "pageflows",
    mediaKind: "css-motion",
    motionSpec: "桌面端鼠标接近时最大位移 8px，离开用 spring 回弹；触屏只保留 press feedback。",
    useWhen: ["主 CTA", "导航高亮", "可探索的案例入口"],
    avoidWhen: ["密集表单", "表格行操作", "移动端主流程"],
    designSignals: ["可点击感增强", "反馈不打扰阅读", "移动端降级"],
    frontendNotes: ["pointer fine 才启用", "transform 不影响布局", "focus state 不依赖 hover"],
    tags: ["cta", "interaction", "microfeedback", "desktop"],
    directionFit: ["soft-intelligent", "experimental-premium"],
  },
  {
    id: "m-scroll-reveal-system",
    patternId: "p10",
    title: "滚动揭示编排系统",
    sourceId: "pageflows",
    mediaKind: "animated-gif",
    motionSpec: "同组元素错峰 80-140ms，图片先出现，文字随后进入，CTA 最后确认。",
    useWhen: ["长落地页", "产品说明", "案例故事"],
    avoidWhen: ["后台工具", "首屏必须立即展示全部内容的页面"],
    designSignals: ["先视觉后文字", "错峰节奏", "减少动画偏好可关闭"],
    frontendNotes: ["data-reveal delay token", "server render 初始可读", "mobile 降低位移距离"],
    tags: ["scroll", "story", "landing", "motion"],
    directionFit: ["soft-intelligent", "experimental-premium"],
  },
  {
    id: "m-gesture-gallery",
    patternId: "p11",
    title: "手势素材画廊",
    sourceId: "mobbin",
    mediaKind: "video",
    motionSpec: "横向滑动带惯性，卡片吸附到中心，边缘保留下一张预览。",
    useWhen: ["移动优先展示", "作品集图库", "案例轮播"],
    avoidWhen: ["桌面信息检索", "需要 SEO 展开内容的页面"],
    designSignals: ["滑动反馈清晰", "边界有阻尼", "有可发现的控制"],
    frontendNotes: ["scroll-snap", "touch-action pan-y", "键盘左右键支持"],
    tags: ["mobile", "gesture", "gallery", "snap"],
    directionFit: ["experimental-premium", "soft-intelligent"],
  },
  {
    id: "m-feedback-loop",
    patternId: "p12",
    title: "异步反馈闭环",
    sourceId: "pageflows",
    mediaKind: "css-motion",
    motionSpec: "点击后 100ms 内进入 loading，成功用 600ms check reveal，失败保留恢复入口。",
    useWhen: ["AI 生成", "上传分析", "表单提交", "保存设置"],
    avoidWhen: ["纯展示页面", "没有异步状态的静态内容"],
    designSignals: ["即时响应", "进度可见", "错误可恢复"],
    frontendNotes: ["idle/loading/success/error 四态", "disable double submit", "错误文案绑定 next action"],
    tags: ["agent", "async", "loading", "state"],
    directionFit: ["calm-professional", "soft-intelligent"],
  },
];

export function getMaterialSourceById(sourceId: string): MaterialSource | undefined {
  return MATERIAL_SOURCES.find((source) => source.id === sourceId);
}

export function getMaterialAssetsByPatternIds(patternIds: string[]): MaterialAsset[] {
  const idSet = new Set(patternIds);
  return MATERIAL_ASSETS.filter((asset) => idSet.has(asset.patternId));
}

export function getMaterialAssetsForDirection(directionId: string): MaterialAsset[] {
  return MATERIAL_ASSETS.filter((asset) => asset.directionFit.includes(directionId));
}

export function buildMaterialContextForAgent(): string {
  return MATERIAL_ASSETS.map((asset) => {
    const source = getMaterialSourceById(asset.sourceId);
    return [
      `${asset.patternId}/${asset.id}: ${asset.title}`,
      `source=${source?.name || asset.sourceId}`,
      `media=${asset.mediaKind}`,
      `signals=${asset.designSignals.join("、")}`,
      `motion=${asset.motionSpec}`,
      `frontend=${asset.frontendNotes.join("；")}`,
      `fit=${asset.directionFit.join(",")}`,
    ].join(" | ");
  }).join("\n");
}
